### ISSUE TITLE
页面旋转90度，touch方向怎么改变

### ISSUE THREAD

**Issue by liliang8858** [git-onepixel/Guesture#3]
如题

**Comment by git-onepixel** [comment]
页面旋转90度，指的是屏幕旋转的适配，还是希望卡片垂直切换？

**Comment by liliang8858** [comment]
手机自动旋转是锁住的，  就用样式强制旋转了页面 90 度，    这个手机手动横过来拿，进行上下滑动的时候无效，只有左右滑动的时候，屏幕才是上下滑动

**Comment by liliang8858** [comment]
> 页面旋转90度，指的是屏幕旋转的适配，还是希望卡片垂直切换？

是这样的需要，这个时候，进行左右滑动，才相当于是上下滑动     ，就是能不能矫正 touch 方向

**Comment by git-onepixel** [comment]
了解了您的意思，这个问题处理起来会比较麻烦，需要一些时间来处理。
不过可以先尝试一下变通方案：不旋转容器，只旋转最里面的图片，就可以达到目的。

**Comment by git-onepixel** [comment]
忘记了，当前项目很久不维护了
上面提供的方案请在这里做尝试：https://www.npmjs.com/package/vue-html-slider

**Comment by liliang8858** [comment]
> 了解了您的意思，这个问题处理起来会比较麻烦，需要一些时间来处理。
> 不过可以先尝试一下变通方案：不旋转容器，只旋转最里面的图片，就可以达到目的。

谢谢
